//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu
    {
        public SysMenu()
        {
            this.SysMenu1 = new HashSet<SysMenu>();
            this.SysMenuSysRoleSysOperation = new HashSet<SysMenuSysRoleSysOperation>();
            this.SysOperation = new HashSet<SysOperation>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public string Url { get; set; }
        public string Iconic { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public string IsLeaf { get; set; }
    
        public virtual ICollection<SysMenu> SysMenu1 { get; set; }
        public virtual SysMenu SysMenu2 { get; set; }
        public virtual ICollection<SysMenuSysRoleSysOperation> SysMenuSysRoleSysOperation { get; set; }
        public virtual ICollection<SysOperation> SysOperation { get; set; }
    }
}
